import type { LocalizedString } from "./i18n";

export const SAMPLE_CHAPTER_TITLE = "PRÓLOGO";

export const SAMPLE_PARAGRAPHS: LocalizedString[] = [
  {
    "pt-br": "Aos poucos, todos os convocados chegavam ao local designado no convite. Isso aconteceu por toda a manhã daquele dia ensolarado de verão, o terreno da mansão da encosta era vasto e apesar dos bosques ao redor, era muito aberto também, e por conta disso, os ventos trazidos pelas águas do Mar do Severn quase sempre sopravam suaves e frescos. Alguns dos convidados preferiam ostentar belas carruagens para embasar uma entrada triunfal, no entanto, outros não faziam questão de camuflar suas origens, estes vinham simplesmente a cavalo. A regra era explícita, e todos ali sabiam muito bem disso, nenhuma identidade real é permitida! Capa, capuz e máscaras eram de uso obrigatório, assim como pseudônimos também, o que muitos gostavam de chamar de \"nome de guerra\".",
    en: "Enim cupidatat quasi adipiscing do quisquam error incididunt pariatur rem elit unde laboris. Tempor qui sunt sed ex tempor accusantium culpa. Quisquam laudantium et nisi illo illo rem elit. Adipiscing nisi consectetur doloremque sit magna in sunt aliqua voluptatem et totam voluptate doloremque. Ut rem totam inventore nostrud excepteur incididunt accusantium quia sed. Ab ullamco perspiciatis dicta error culpa eos velit. Rem mollit pariatur reprehenderit ea sequi quis nemo eos ea eiusmod totam reprehenderit natus perspiciatis. Aspernatur deserunt irure ipsa do et omnis sunt minim consequuntur eu enim laborum. Consectetur beatae do magni doloremque totam sequi porro velit eu explicabo fugiat eaque perspiciatis. Sed quia tempor duis id nemo beatae sed elit aspernatur nemo voluptate veritatis totam dicta.",
  },
  {
    "pt-br": "As pessoas da cidade de Handestiny há muito já haviam aprendido a não fazer perguntas quanto àqueles que se dirigiam à mansão da encosta, afinal, seus assuntos acabam sempre em sangue e sumiço, todavia, nada tinham contra sua presença ali, na verdade estavam em polvorosa com o número crescente de tantos forasteiros, que há dias não paravam de chegar à cidade, isso significava fartura, e de onde jorrasse a fonte do lucro, bom, a isso pouco se dava importância...",
    en: "Irure quia occaecat beatae fugiat dolor anim nulla minim quae labore perspiciatis elit laboris dolores. Dolore odit ea cupidatat cupidatat perspiciatis eiusmod minim deserunt non accusantium aute. Porro qui amet accusantium aute ipsam sunt nulla dicta sint. Enim eiusmod veniam enim aliquip architecto aliquip ipsum laborum dolorem aperiam. Consequat irure lorem aliqua sunt error excepteur quae laudantium velit. Explicabo sit omnis ab quasi vitae odit adipiscing mollit eos.",
  },
  {
    "pt-br": "O anfitrião tinha um nome conhecido apenas através de sussurros, era algo que as pessoas não gostavam de dizer levianamente, afinal, nunca se sabe quem poderia estar ouvindo, de qualquer forma, todos no evento estavam à vontade sob sua proteção, que não se dava por sua idade avançada, baixa estatura e robustez, mas sim por ser perigoso e invencível, como diziam as histórias. Berdox era um grande líder a ser seguido e admirado, pois nada neste mundo trazia mais benefícios do que a simples presença de sua influência, sua palavra então era conhecida como \"a lei acima da lei\" e por isso, mesmo que ninguém se dirigisse assim a ele, era considerado por todos como \"o rei nas sombras\". Eram raros aqueles que mantinham uma opinião pública contrária à sua figura, estes eram os autodeclarados \"homens de honra\", e é claro que não eram muito populares, afinal, dependendo do que ousassem dizer, as consequências logo viriam, e quase sempre, eram severas, severas demais... pois costumavam castigar não somente a eles, mas os outros a sua volta também, uma espécie de lição que os fazia de exemplo aos demais que estivessem motivados a fazer o mesmo. O velho Berdox sempre sabia quem eram estes tais \"incitadores\", como gostava de os chamar, tinha todas as informações sobre eles e os seus, tanto aqueles ao redor como os distantes, e apesar de contraditório, tinha certo apreço por aqueles que realmente eram o que diziam ser, pois nem todos os honestos eram realmente honestos.",
    en: "Cupidatat cupidatat non cupidatat ut est inventore non elit nostrud sed ullamco officia ad labore eu. Ut lorem laudantium enim error incididunt pariatur quae. Do ullamco quae sint enim inventore commodo fugiat. Id et labore dolor laborum anim est est voluptate eiusmod aliqua ut fugit. Odit consequat est dolorem explicabo ad iste dolor ullamco natus pariatur aliqua explicabo. Sit magni natus reprehenderit veritatis amet tempor nemo dolor consequat iste pariatur minim nulla dolores nisi. Voluptatem eos unde cillum inventore nisi quae neque ratione magni sit nostrud neque ex porro non. Exercitation iste perspiciatis nulla aspernatur sit sit sequi aute id consequat. Explicabo ipsa fugiat deserunt neque voluptas fugiat pariatur eiusmod nisi ut. Id exercitation eu ullamco est ab quae quia lorem est quasi. Nesciunt veritatis eiusmod dolorem architecto et occaecat ratione quia consequuntur exercitation est veniam. Sequi inventore cillum tempor nesciunt voluptas cupidatat anim non fugit eiusmod voluptas ad minim. Sit enim aperiam anim neque quasi aliqua quae quisquam eaque. Architecto fugiat enim accusantium accusantium dolore dolor ipsum nesciunt voluptas quasi ut natus fugit magna. Nostrud quisquam laboris sit commodo laboris in unde ex magni aperiam esse consequat voluptatem. Dolorem dolore elit odit nulla mollit architecto rem porro iste sunt quisquam unde dolore. Enim natus omnis dolor officia eos quis ipsa lorem eos nesciunt enim veniam aliqua id ab. Doloremque elit esse dicta iste natus doloremque est ratione.",
  },
  {
    "pt-br": "– \"Por vezes, as sombras são mais reveladoras do que a própria luz!\" – Corriqueiramente, dizia o velho Berdox.",
    en: "Doloremque elit ea nostrud aute consectetur dolores incididunt unde. Doloremque sit magni sed officia esse quae unde ipsa omnis exercitation explicabo aute deserunt omnis.",
  },
  {
    "pt-br": "Certa vez, foi questionado sobre o motivo de manter-se tão discretamente neste mundo, ao invés de tomar logo o poder vigente. Depois de um breve silêncio, ele então respondeu aos presentes.",
    en: "Neque est unde ea nemo iste consequat doloremque exercitation quia deserunt magna sunt et cupidatat officia. Do beatae ex culpa do laboris beatae reprehenderit ratione et eos enim quia. Aliqua commodo magna anim nisi fugit incididunt cupidatat laborum ad beatae dolorem nisi.",
  },
  {
    "pt-br": "– Entre outras coisas, o trono real é também uma prisão, já o governo das sombras é muito mais atrativo aos meus ideais, pois sua discrição permite alcançar muito além de qualquer fronteira, a tudo e a todos aos quais a devida influência for capaz de conter. Os presentes ficaram pensativos sobre tais ideias.",
    en: "Ipsam qui omnis non eu sunt exercitation nulla velit tempor. Dolor eu accusantium mollit officia ipsam dolor occaecat cillum iste ab in omnis. Labore ratione aliquip ut eiusmod consequat duis consectetur eos. Duis consequuntur dolore porro culpa dolor vitae porro consequat non. Error omnis totam perspiciatis nemo esse tempor aute elit nesciunt.",
  },
  {
    "pt-br": "– Quando eu me movo, ninguém me vê. O que eu movimento, ninguém sabe. Quem está em cada ponta, ninguém conhece... – Completou ele, fazendo todos tentarem calcular o seu poder.",
    en: "Culpa do duis dolor inventore tempor nesciunt consequat eiusmod ipsa. Sed consequat amet et mollit ipsum eu accusantium sunt duis ab. Consectetur natus ipsam ex labore ad consequat adipiscing quis exercitation.",
  },
  {
    "pt-br": "– Sem falar que... eu ficaria ridículo com aquela peruca...",
    en: "Illo voluptate natus magni ullamco in deserunt unde vitae veniam duis fugiat.",
  },
  {
    "pt-br": "Além dos risos e gargalhadas, aqueles aristocratas também riam de alívio, demonstrando assim o receio que tinham em estar ali, em sua presença, pois tal proximidade já bastava para poder configurar um claro ato de traição diretamente contra a nobre coroa britânica, algo que era punível com execução naqueles bons dias. A ironia, porém, era que aqueles mesmos homens, sem exceção alguma, também usavam perucas semelhantes à do rei.",
    en: "Commodo amet ipsum dolor aspernatur unde accusantium nostrud. Id ea deserunt ut architecto porro quasi qui architecto perspiciatis voluptatem dolorem cupidatat unde voluptate explicabo. Aliquip eu exercitation dolorem ipsam aspernatur inventore magna non fugiat adipiscing. Ipsum do illo odit commodo qui ad elit eiusmod beatae. Unde beatae irure eaque ea explicabo in consectetur mollit quis ad duis deserunt lorem. Pariatur cillum accusantium esse ea amet voluptate laboris nulla quis lorem cillum.",
  },
  {
    "pt-br": "O raiar do dia havia sido um grande espetáculo, e a manhã que trouxe consigo seguia da mesma forma, uma oportunidade raríssima que Berdox não costumava desperdiçar. Era um costume estranho esse que tinha, por incontáveis vezes ele passava noites em claro e permanecia ali, imóvel nos jardins particulares ao fundo de sua bela casa, estes eram exuberantes e coroavam a propriedade. Seus tons de verde abrigavam uma grande variedade de flores, entre elas, destacavam-se arranjos de rosas vermelhas, orquídeas e violetas, a poda artística estava sempre impecável, contudo, caminhava pouco entre elas, seus passos eram não mais do que o necessário para que encontrasse seu posto preferido, onde se punha em silêncio e permanecia incansavelmente ali de pé, apenas observando o mesmo mar e o mesmo horizonte. Era como alguém que admira profundamente uma pintura, mas na verdade ninguém nunca soube o que se passava em seus pensamentos.",
    en: "Eiusmod id aute unde quasi exercitation ea unde eos lorem tempor consequat porro tempor. Non aperiam consectetur cupidatat dolor reprehenderit reprehenderit illo aliquip eiusmod. Sit consequuntur enim architecto quia ratione eaque occaecat magni esse voluptas perspiciatis enim irure voluptas ab. Consectetur quisquam dolorem quia omnis illo culpa aspernatur nemo neque. Magna natus consequuntur unde laudantium dolorem porro nesciunt dolor quisquam dicta rem nesciunt quia dicta explicabo. Eiusmod sit consectetur magna inventore pariatur ut sint dolorem deserunt doloremque. Illo dolor illo error dicta ea laborum consequat. Mollit nesciunt sed fugit unde error tempor architecto. Sed fugit odit id commodo neque do dolor consequat ex aspernatur consequuntur ullamco aliquip odit quasi. Perspiciatis dolor sint do est dicta irure dolores consectetur quae illo veritatis exercitation do eaque. Cillum commodo quasi fugit explicabo reprehenderit ab laudantium magna ipsum.",
  },
  {
    "pt-br": "A essa altura, a manhã já estava quase encontrando a tarde, a recepção acontecia como planejado e logo acabaria também, felizmente tinha propósitos de entretenimento, de modo que seu andamento não exigia a graça de sua presença, com mais algum tempo então, foi até o mirante mais a frente para observar o mar e aproveitar o sol de lá por mais algum tempo. As águas quebravam suas ondas suavemente nas areias da praia e nas rochas da encosta também, o sol estava ameno e o vento suave, embalando assim a alegria dos pássaros e dos esquilos que brincavam pelos jardim. As melhores horas de paz em sua vida ele havia passado naquele exato ponto, parado como uma sentinela de pedra, apenas respirando e admirando o mar e os céus, o poder era interessante, porém, nada mais além disso parecia agradar ao velho homem.",
    en: "Elit laborum duis vitae incididunt explicabo laboris vitae laborum in ipsam iste irure anim anim. Dolores et accusantium exercitation voluptate eiusmod id dolor in mollit do porro unde deserunt duis. Ullamco ullamco do rem tempor aliqua fugit natus consequat pariatur dolore ipsa porro illo. Aute labore ipsam pariatur aliquip perspiciatis laborum cupidatat sit ad lorem laborum dicta deserunt non reprehenderit. Sunt fugiat sint velit et quia cillum lorem esse consequuntur. Quia cupidatat et exercitation quia ipsum odit in commodo excepteur sed cupidatat occaecat. Pariatur culpa consequuntur aute sit adipiscing aute ut adipiscing. Inventore enim ea duis qui omnis velit nostrud dolores excepteur ratione culpa. Neque magni illo non accusantium accusantium ullamco voluptas. Adipiscing aspernatur proident deserunt quae consequuntur magna veritatis irure.",
  },
  {
    "pt-br": "– Desculpe interromper, Senhor, mas a reunião deve ter início em alguns minutos. – Disse um de seus seguranças pessoais, lhe trazendo de volta de onde estava.",
    en: "Adipiscing accusantium dolore minim id sunt eu irure reprehenderit commodo odit odit quasi consequat non. Reprehenderit est doloremque beatae cupidatat et minim veritatis ad do ullamco.",
  },
  {
    "pt-br": "Nenhuma resposta veio de Berdox. Não chegou a abrir os olhos, nem ao menos virou-se, não expressou nenhuma reação, como sempre acontecia. Ele pensava ter autoridade até mesmo sobre os ponteiros do relógio e por isso não se preocupava, não se apressava, o andamento de qualquer evento seguiria o ritmo conforme sua vontade ditasse que seria, então foi deixado a sós no mirante, o local onde recarregava a paz em sua alma.",
    en: "Neque perspiciatis accusantium nisi deserunt cillum magni deserunt culpa magna accusantium nostrud ea tempor veniam eu. Tempor velit ex excepteur consequat neque laudantium exercitation dolor fugit proident occaecat proident fugit natus ullamco. Duis eu consequuntur elit perspiciatis aute totam pariatur dolore dicta unde natus illo sequi. Tempor duis ea occaecat non veritatis deserunt qui voluptate dolor porro. Dolore amet culpa ipsam magni nesciunt id aperiam.",
  },
  {
    "pt-br": "No salão principal da grande mansão, o evento acontecia com muita elegância e fartura, comida e bebida à vontade! Ao som de boa música animada, muitas pessoas pouco vestidas dançavam provocantemente para embalar os mais variados dos desejos, outros deles entretinham os presentes com malabarismos, pirotecnia, teatrinhos cômicos e outros truques circenses. Todos aproveitavam a agradável recepção enquanto serviam seus estômagos e seus olhos, entre uma coisa e outra, socializavam histórias e parcerias, ou então encontravam diversão nos jogos de cartas e outros de mais azar, às vezes, as apostas iam muito além do dinheiro. O anonimato era obrigatório até mesmo ali, os trajes longos normalizavam as aparências e as máscaras, que por sua vez, mistificavam os disfarces, dando a eles tons ainda mais exóticos, algumas, porém, acabavam por dificultar a alimentação, então aqueles que queriam se fartar ocupavam mesas discretas que havia aos montes pelos cantos e pelo centro do salão, cuja iluminação era propositalmente muito baixa, as cortinas suntuosas estavam um pouco abertas justamente para fornecer mais discrição.",
    en: "Lorem do cupidatat quisquam natus sit anim deserunt ea ratione ut nisi enim enim iste. Quisquam voluptas nemo veritatis dolor magni mollit eiusmod accusantium. Lorem ratione dolore aliquip laudantium amet veritatis quia. Dolore illo commodo natus inventore qui nemo magni labore incididunt do reprehenderit. Rem nostrud occaecat consequat nisi sequi eaque lorem ipsum error reprehenderit mollit aute velit veritatis quia. Id natus ex accusantium ea sit proident ipsam quasi voluptate elit. Nostrud perspiciatis vitae veritatis sunt eiusmod commodo aliquip. Excepteur aliquip perspiciatis amet nemo eu quia sunt pariatur dicta cupidatat exercitation lorem nesciunt. Odit dolor unde sed ullamco perspiciatis exercitation voluptate dolores porro nostrud aliquip. Nisi consequat magni in ut ab perspiciatis quae quis nisi laborum sunt beatae elit eaque. Cupidatat adipiscing laboris sit eaque aliqua sunt adipiscing ipsam elit. Cupidatat deserunt quia velit aspernatur labore eiusmod minim cillum nostrud. Quasi natus fugit anim amet voluptate beatae voluptas sint quia. Cillum officia minim ut lorem eiusmod aute eiusmod fugiat sunt et doloremque magni.",
  },
  {
    "pt-br": "Blarinh, conhecido como \"Dedos Mortos\", tirava vantagem deste sistema de sigilos com maestria, onde através de sua lábia convincente, obtinha o máximo de informações possíveis sobre os outros convidados a quem conseguisse persuadir de qualquer coisa, se conseguisse minimamente identificar qualquer um deles, poderia então construir um belo dossiê que lhe renderia um bom lucro, além disso, esquadrinhava as instalações da mansão com muita atenção também, com seu olhar atento, procurava guardar cada detalhe relevante para depois replicá-los em desenhos de plantas que certamente renderiam um bom dinheiro caso encontrasse o comprador certo. Era uma oportunidade única aquela, por isso seu empenho era total. Havia muito mais o que roubar dali também, obras de arte como quadros, estatuetas e outros objetos finos estavam presentes em abundância por todos os cantos, sem falar das joias e outras preciosidades que deveriam estar escondidas nos cofres... esse pensamento o fez salivar. De qualquer forma, seus objetivos eram profanos, até mesmo para um lugar como aquele, até mesmo para gente como aquela... apesar de serem cruciais para manter seu disfarce, não se importava tanto assim com as regras, afinal, não poderia sofrer em nada com as consequências, e sendo assim, não planejava sair dali de mãos abanando.",
    en: "Sint nulla dolores quisquam voluptate quisquam nesciunt qui tempor adipiscing ipsam. Exercitation excepteur voluptatem deserunt nostrud esse pariatur odit id sit illo proident ea neque illo. Consectetur sint amet anim sed nesciunt elit commodo nostrud fugit sed ipsa eu pariatur. Cillum quae consectetur consequat fugit quia explicabo velit aute reprehenderit lorem voluptas. Sit quisquam aliquip ut id quia anim eos occaecat. Qui porro perspiciatis dolore perspiciatis quis ipsum nesciunt odit reprehenderit quisquam explicabo. Ipsa ex esse amet velit mollit pariatur ratione ratione eaque. Omnis exercitation cupidatat consequuntur ad ea proident sed quasi. Est accusantium voluptatem esse ad culpa ut do. Ab eiusmod ullamco incididunt sunt perspiciatis ipsam deserunt veniam aliquip magna sunt. Ab vitae ex fugit error dolor eos beatae magni et eos quia in in aute. Excepteur commodo odit consequat exercitation officia ea quis ea ex enim irure. Esse sed cupidatat commodo ea unde natus aliquip quasi neque incididunt. Amet ut lorem id porro aliquip quia deserunt excepteur consectetur in aliquip et adipiscing nostrud. Do excepteur omnis amet veniam deserunt ipsa consequat eos eos beatae. Ut inventore eaque ipsam ab fugiat laboris amet. Eu aliqua consectetur ullamco commodo amet eaque aspernatur quasi ullamco porro ipsum porro.",
  },
  {
    "pt-br": "– Isso, continuem comendo e se exibindo, seus grandes idiotas luxuriosos... mal fazem ideia de quem realmente sou... se soubessem que o verdadeiro banquete é este que vossos egos produzem sem o menor pudor... se soubessem o imenso estrago que farei em vossas vidas com essas informações... se soubessem então, de certo se manteriam calados diante das armadilhas que lanço no ar...",
    en: "Proident vitae excepteur quis ab voluptate do ullamco amet sequi perspiciatis accusantium est. Proident incididunt sequi cupidatat architecto accusantium enim inventore error. Quasi ad cupidatat nemo duis proident irure beatae voluptate. Adipiscing voluptate fugit laudantium nulla sunt sunt dolor amet dolores nesciunt pariatur veritatis exercitation. Aspernatur non ullamco lorem qui ad culpa labore quisquam tempor non totam pariatur mollit.",
  },
  {
    "pt-br": "– O famoso \"Dedos Mortos\", não é mesmo? – Disse alguém, chamando sua atenção enquanto passava pelo grupo. O salão estava repleto de fumaça de charuto e de barulho de diversão comportada.",
    en: "Dolore ipsum adipiscing accusantium aliqua veritatis neque cupidatat tempor totam. Odit unde minim aliqua fugiat irure ad iste minim sed ut occaecat laborum. Reprehenderit dolore quia consectetur est velit adipiscing ipsa inventore occaecat tempor.",
  },
  {
    "pt-br": "– Parece que fui descoberto! – Brincou Blarinh, se servindo de uma taça de espumante diretamente da bandeja da garçonete seminua, que cruzava seu caminho.",
    en: "Inventore ratione sit nisi ab non quae dolor exercitation dolorem. Quis laudantium laboris consectetur non iste ad occaecat nulla et enim ea voluptas porro nostrud.",
  },
  {
    "pt-br": "– E o que me denunciou? Senhor...",
    en: "Doloremque quia consequuntur vitae amet beatae quia esse.",
  },
  {
    "pt-br": "– Sou \"O Silêncio\" e estes são \"Amigo Feliz\" e \"A Bela Donzela\". Venha, por favor, junte-se a nós. Sorrindo de empolgação, Blarinh se aproximou sem nem ao menos hesitar, pensando assim ter encontrado boas presas, contudo, talvez fossem eles os caçadores. Aquele jogo era perigoso e excitante demais para ser jogado sozinho. Os três eram altos, esguios e tinham trajes elegantes e escuros, o deles completamente negros, o dela era o mais escuro que o vermelho poderia ser. A similaridade deles parecia ser proposital, indicando uma antiga aliança talvez, um sinal claro, que fez Blarinh agir ainda com mais cautela.",
    en: "Occaecat eaque mollit accusantium dolor illo eos voluptate quasi. Voluptate rem ea culpa occaecat architecto excepteur deserunt unde officia veniam dolor lorem ab. Anim ex deserunt magni ab eos porro mollit quia veniam neque id non ut sed. Nulla qui pariatur tempor nesciunt officia unde omnis architecto consectetur. Inventore dolore eiusmod aspernatur velit eos voluptas omnis. Adipiscing consequuntur unde sint quasi ratione magna sit sit. Quae aspernatur explicabo porro labore nostrud dolore laborum irure. Dicta ratione voluptas nisi sed dolorem fugiat quae consequuntur commodo. Esse quae aute porro mollit aliqua commodo unde est ullamco.",
  },
  {
    "pt-br": "– O reconheci de imediato pelo ornamento da máscara, sou um grande fã de seu trabalho! – Confessou \"O Silêncio\", claramente emocionado, pelo encontro.",
    en: "Quae unde ex velit excepteur amet exercitation quis non ad inventore aute. Sint minim sequi ratione consequat labore dolores natus adipiscing inventore sit pariatur deserunt.",
  },
  {
    "pt-br": "– Ah, sim! Claro... foi... por isso mesmo que eu o entalhei aí... somente meu público saberia admirar tais ações, não é mesmo?",
    en: "Iste rem explicabo ut commodo error illo sit cupidatat odit nesciunt excepteur consequat sint excepteur totam. Pariatur cillum magni eiusmod officia aliquip veniam quae fugit adipiscing.",
  },
  {
    "pt-br": "– Respondeu nervosamente Blarinh, com um sorriso um tanto desajeitado e incerto, em sua afirmação improvisada. O batom vermelho nos lábios suculentos de \"A Bela Donzela\" era muito convidativo, deixava-os brilhantes como o orvalho escorrendo de uma rosa. Sua meia máscara fina e curta não escondia a delicadeza de seu rosto pálido e maquiado, suas joias chamativas foram escolhidas justamente para ornar perfeitamente com seus cabelos ruivos e sua boca vermelha como sangue também. Suas vestes finas e levemente fúnebres eram o contraste perfeito com a personalidade sedutora que tinha, a mulher era puro desejo escarlate, e sendo ela tão simpática com ele, Blarinh, sendo um jovem faceiro, deixou-se levar por seus encantos e com o trio, ficou ali conversando por algum tempo. Tudo ocorreu bem, os três eram pessoas bem ajustadas e seus assuntos eram... um tanto perturbadores... assim como o de todos os demais convidados, naquele dia. [...]",
    en: "Porro iste commodo voluptate inventore rem architecto velit aspernatur lorem fugit amet. Enim in quae illo qui sunt omnis pariatur adipiscing dolore laborum. Quae quasi consectetur dolor adipiscing lorem laudantium nulla reprehenderit ut iste. Error nisi proident rem reprehenderit aperiam magna ullamco pariatur ab dolorem id ad. Ipsum nesciunt ea ipsam enim deserunt incididunt sed inventore aliqua. Non neque consequat ipsum elit veritatis quisquam doloremque fugiat eaque veritatis rem. Ipsa iste aspernatur perspiciatis ea minim lorem consectetur elit error sit non quis ex ad. Eos ut ipsum quae accusantium architecto exercitation aliqua. Exercitation iste ipsa veritatis unde veritatis veritatis sunt porro quae veniam omnis voluptate sed. Illo adipiscing voluptas ratione est quia error lorem sint dolor qui fugit. Eiusmod odit quasi deserunt veniam nisi ut consequat aliquip veritatis amet et cillum fugit explicabo. Quia adipiscing duis inventore accusantium vitae qui dicta ratione iste consequat in.",
  },
  {
    "pt-br": "Por mais algumas horas, Blarinh conheceu outros diversos ali presentes com quem trocou as mesmas frivolidades, histórias curtas, contatos profissionais e todo tipo de informação superficial que pôde. Acabou descobrindo nas entrelinhas destas interações, que não era o único mal-intencionado do lugar. Sem nenhuma entrada triunfal, Berdox surgiu no palco, para finalmente receber aqueles a quem invocou naquele dia, o velho estava atrasado, mas ninguém pareceu se importar, já que o tempo investido ali estava sendo praticamente comprado por ele com o que havia de melhor em valor, depois do dinheiro. A voz grave e pesada do velho logo chamou a atenção de todos os presentes, que respeitosamente silenciaram suas atividades pecaminosas para lhe prestarem total atenção.",
    en: "Eiusmod unde ipsum minim consequat ex quia fugit exercitation ad fugit. Nostrud occaecat cillum eaque ex sint sit illo explicabo beatae quia error id. Quia natus nemo lorem sit sit qui voluptas aliquip totam voluptate sequi laboris cupidatat ab. Laudantium minim aliqua amet sit labore ut ab ad. Aliqua nemo sit sit consectetur magna explicabo veritatis inventore consectetur nemo sed odit. Sed sit aperiam magni pariatur exercitation porro porro. Beatae sed consequuntur quia occaecat ut ea ullamco ullamco labore amet amet dolor neque consequuntur inventore. Quisquam consequuntur illo illo irure est incididunt dolore incididunt. In velit eu culpa consequat dolor fugiat commodo irure adipiscing quia. Esse dolores ipsa unde id dolor irure ab fugit sit ratione proident sit.",
  },
  {
    "pt-br": "– Uma feliz tarde a vocês, meus estimados associados! Muito alegremente, todos eles o cobriram de aplausos elegantes, aqueles mais embriagados, o exaltaram e gritaram elogios exagerados, causando risos de agradecimento no velho, que apesar de ter a crueldade moldada no rosto, também sempre fora bemhumorado, um limite este de difícil distinção, sendo uma aposta perigosa demais para se arriscar fora de multidões mascaradas, como era aquela.",
    en: "Iste dolores incididunt fugiat id ipsam adipiscing error laudantium laboris quia amet quisquam tempor. Minim qui lorem natus exercitation irure magni consequuntur adipiscing lorem fugiat laborum. Laborum explicabo sequi quisquam quis perspiciatis aperiam fugiat dolorem. Consequat totam ad irure porro laboris nemo aliquip perspiciatis minim labore inventore dolores eiusmod laborum ratione. Ratione ut illo esse nulla incididunt non cupidatat fugit tempor culpa veritatis sit excepteur ullamco reprehenderit.",
  },
  {
    "pt-br": "– Muitos de vocês atenderam ao chamado e vieram de muito longe para este dia maravilhoso ao qual partilhamos com extrema alegria, e a isso, sou muito grato! Aos outros poucos ausentes, bom... estes serão caçados, é claro... há pouco, decidi que não sustentaremos mais dissidentes como estes! – Todos se espantaram, surpresos pela dura decisão, mas isso durou pouco, pois logo em seguida, Berdox complementou dizendo que em breve revelaria o preço por suas cabeças.",
    en: "Culpa voluptatem unde minim sint illo aliquip mollit dolore error eaque consequuntur. Fugiat rem esse iste enim quia deserunt architecto. Odit esse minim anim officia explicabo dolores commodo rem aliquip dolore cillum anim veritatis nemo ex. Nostrud duis reprehenderit consequuntur ipsam quisquam quia ab enim voluptas enim ea voluptas esse ipsa iste. Ad ex esse nostrud consequat aspernatur ut minim architecto ut exercitation occaecat enim. Sequi reprehenderit aspernatur reprehenderit qui aute exercitation ut inventore ut.",
  },
  {
    "pt-br": "A alegria restaurada na plateia o fez sorrir de canto, demonstrando que saboreava com muito prazer o poder que exercia sobre as pessoas. – Sim... sim... parece que muitos aqui vão prosperar muito, no entanto, por ora peço gentilmente que se preparem para encerrar momentaneamente seus assuntos, pois de agora em diante, faremos uma pausa da diversão para tratar do verdadeiro motivo pelo qual os chamei aqui hoje, negócios futuros!",
    en: "Ullamco occaecat anim amet ipsum non sit sequi qui explicabo nisi unde. Anim dolor aliqua commodo ipsa odit non lorem odit ea sit qui. Dolor aliquip beatae voluptas quasi eos veritatis nemo rem sit aliquip vitae quis veritatis. Mollit qui velit consequat illo nemo incididunt sunt ea. Quia quia illo ad commodo dolor culpa est mollit dolor ab sit proident iste. Quasi esse eos ipsum occaecat dolorem laborum ut amet commodo. Laboris ad quia ratione exercitation iste fugiat incididunt dolor totam mollit voluptatem ullamco quia id omnis.",
  },
  {
    "pt-br": "Enquanto os serviçais deixavam o local, todos iam então procurando por seus devidos assentos, conforme estava indicado no convite. Instantes depois, Berdox tornou a falar, porém Blarinh não entendia o que dizia, pois falava um idioma estranho que não lhe soava nada familiar. Conforme o discurso do anfitrião progredia, mais preocupado ficava Blarinh, ainda mais pois parecia ser o único assim, e para não ser descoberto, passou então a emular as mesmas reações dos outros ao seu redor, cujos comentários ele entendia normalmente, e isso só aumentava a estranheza da situação. Aos poucos, o crescente nervosismo lhe tirava a compostura que se esforçava tanto para manter, era como ver o tempo fechando em alto mar estando a bordo de uma canoa sem remos.",
    en: "Inventore sequi dolorem excepteur iste eu proident odit. Ullamco dicta quis cupidatat omnis magni et aspernatur quae nulla inventore elit commodo aute sint. Elit ipsum do sunt sunt illo nemo vitae nulla rem consequat ut nisi reprehenderit. Natus nisi nesciunt cupidatat anim laboris minim dolore eos sed neque nesciunt inventore nostrud. Veritatis doloremque voluptas nisi porro aliqua nulla beatae inventore dolorem porro sequi porro proident anim. Magni accusantium quasi dolore eos dolorem id nulla ratione dolor aliquip duis. Dicta commodo culpa vitae quis est lorem neque voluptas nesciunt aute nulla ea quasi. Esse est laborum culpa ab inventore eiusmod architecto pariatur enim reprehenderit sit. Elit eiusmod quisquam laudantium esse ratione magna natus dolorem fugiat inventore rem ipsum architecto.",
  },
  {
    "pt-br": "– Mas que droga está acontecendo aqui??? Quando assumi a identidade de Blarinh, não encontrei nada sobre outras línguas... e isso não é nada bom... nada bom mesmo!",
    en: "Ullamco do quasi in commodo ipsa incididunt rem. Sit aliquip quis eos deserunt fugiat ratione enim ullamco non. Minim quae explicabo ipsa ratione tempor beatae accusantium ratione inventore quia reprehenderit exercitation perspiciatis explicabo laboris.",
  },
  {
    "pt-br": "A preocupação já havia cruzado as fronteiras do fingimento. Desconcentrado, ele foi o único que não riu do que Berdox disse.",
    en: "Eiusmod odit quia officia beatae labore doloremque et consequat sunt aliquip quisquam magna id perspiciatis doloremque. Est anim aliqua nemo laborum ea perspiciatis minim.",
  },
  {
    "pt-br": "– Talvez ninguém tenha percebido... – Pensava nervosamente, torcendo para que a máscara estivesse encobrindo suas reações tardias.",
    en: "Eaque amet odit lorem ad quia esse anim nemo laudantium perspiciatis beatae in quia anim excepteur. Sunt vitae do quis inventore pariatur inventore veritatis sit dolor quae consectetur dicta odit.",
  },
  {
    "pt-br": "O discurso do velho seguiu com o mesmo tom e durou por mais algum tempo, até que então todos se levantaram e aplaudiram enquanto seu anfitrião se retirava e deixava o palanque. Tardiamente, Blarinh se pôs a fazer o mesmo que os outros, mas percebeu o receio dos que estavam à sua volta. Os serviçais já voltavam ao recinto e então o clima de festividade logo trouxe a euforia de volta, tranquilizando-o novamente, que de tão nervoso que estava, suava excessivamente. A primeira coisa que fez para se inteirar do que havia perdido, foi procurar por alguém com quem houvesse criado algum vínculo.",
    en: "Neque incididunt omnis est laborum consequuntur aliqua amet laboris quia sunt illo dolore. Incididunt amet architecto pariatur eu id eos natus accusantium dolores ullamco irure qui. Culpa commodo accusantium adipiscing quisquam in in nulla quisquam perspiciatis non cillum unde. Unde fugiat ullamco quasi perspiciatis sequi et cillum nostrud velit quia reprehenderit. Aperiam inventore tempor ratione consectetur non voluptas accusantium non voluptatem. Non reprehenderit ut lorem consectetur nostrud quisquam id. Ratione unde voluptatem quae sint quae aliqua illo. Laboris consectetur beatae inventore mollit illo magni veniam incididunt.",
  },
  {
    "pt-br": "Seu andar já não demonstrava a mesma confiança, estava abalado, tinha de se recompor... – Onde estão os malditos garçons com a bebida...",
    en: "Amet sunt eos incididunt quasi ipsum excepteur quisquam magna ratione. Doloremque ipsam consequat amet reprehenderit quis sunt amet velit dolor qui laudantium.",
  },
  {
    "pt-br": "E foi então que avistou \"A Bela Donzela\", ela acenava para ele de um canto escuro do salão, e sem demoras, foi de imediato até ela.",
    en: "Perspiciatis laudantium iste consectetur quisquam et eos neque. Totam nemo non deserunt sed ipsum dicta occaecat eaque aperiam architecto enim id dolores.",
  },
  {
    "pt-br": "– Nem acredito no que nosso chefe disse! Como é possível?",
    en: "Accusantium ut eiusmod veritatis id laboris enim illo ipsum culpa lorem ipsum dicta beatae.",
  },
  {
    "pt-br": "– Perguntou, a bela moça.",
    en: "Sit tempor laboris et dolore id dolor aute voluptas.",
  },
  {
    "pt-br": "– Não faço ideia alguma, mas confesso que gostaria de entender melhor seus motivos... – Jogou a isca Blarinh, mantendo a pose para tentar encontrar algum caminho em que pudesse seguir sem levantar mais suspeitas.",
    en: "Deserunt aspernatur fugit quis adipiscing pariatur eos fugit quia explicabo sit. Aspernatur magni eiusmod in illo doloremque ipsam perspiciatis mollit beatae. Adipiscing quia amet ipsum elit ipsum quasi dicta porro ab eiusmod occaecat.",
  },
  {
    "pt-br": "– Talvez \"O Silêncio\" possa nos dizer, aí vem ele... – Sugeriu ela.",
    en: "Voluptate aspernatur eaque minim amet dolorem laborum ipsa elit velit excepteur totam.",
  },
  {
    "pt-br": "Ao se virar para receber o admirador, Blarinh não teve tempo para desviar de seu punho fechado, que o acertou com força total bem no meio da cara. A brutalidade do golpe rompeu sua máscara e o atirou diretamente no chão, o gosto de sangue na garganta foi repentino também, pelo barulho do estalo e pela dor aguda, deduziu que o nariz estivesse quebrado. Tudo girava depois do impacto doloroso. Antes mesmo que pudesse deduzir que havia sido descoberto, o vislumbre de uma sola de bota encobrindo sua visão foi a última coisa que viu antes de tudo ficar escuro. Não chegou a desmaiar, não totalmente ao menos. [...] Sentia-se completamente dominado. [...]",
    en: "Id vitae minim aliqua nesciunt labore pariatur veritatis ad illo nesciunt sunt est occaecat eos. Duis ratione consequuntur laudantium cillum in aute elit ab quasi ipsam nesciunt quisquam eaque cillum. Dolorem enim eaque dolorem voluptate rem culpa ea. Occaecat dicta sint ipsa dolores aliquip neque deserunt irure explicabo lorem esse consequat duis. Ad aperiam porro magni ratione consectetur irure dolorem aliqua neque totam aliqua aute dolor. Dicta eos perspiciatis fugiat error eiusmod voluptatem accusantium laborum nesciunt sint exercitation ratione consequuntur voluptas aliquip. Ipsa elit vitae cupidatat anim ipsam ullamco commodo aperiam consequuntur ipsum sequi.",
  },
  {
    "pt-br": "Sem maiores dificuldades, dois homens o suspendiam pelos braços e o arrastavam para longe dali. [...] Alguma coisa o apertava... estava sendo amarrado a algo. [...]",
    en: "Mollit voluptatem tempor error neque nulla dolores sed aliquip cupidatat rem iste consequat dolorem. Esse est unde aperiam exercitation nostrud laboris nostrud tempor quis neque nemo in pariatur totam laudantium.",
  },
  {
    "pt-br": "O forte cheiro de álcool ardeu suas narinas e lhe trouxe de volta, aos poucos recuperou os sentidos, e quando voltou a si, logo se percebeu em uma sala suja e escura, estava sentado e todo acorrentado a uma viga de sustentação, assim como um animal rebelde prestes a ser castigado. À sua volta, estavam próximos ao menos uma dúzia dos guardas que garantiam a segurança do evento, todos ostentavam espadas desembainhadas, nenhum deles fazia contato visual ou então respondia a suas perguntas, sua lábia não mais surtia efeito algum. Então, entraram ali alguns outros mascarados, entre eles estava, Berdox. Se aproximando ainda mais, muito empolgado o velho disse,",
    en: "Non eos iste sit enim ea consectetur perspiciatis excepteur amet ut excepteur illo. Ratione eiusmod enim velit eaque sit fugiat aute iste ipsa dolor incididunt amet ullamco amet. Aperiam laudantium laboris consequat eos aute culpa incididunt deserunt dolores aperiam porro ipsa dolore commodo. Eu exercitation quis sint eiusmod sit adipiscing amet. Excepteur ipsam mollit laborum dolor sed amet eaque inventore cupidatat et ipsam tempor commodo velit laudantium. Veritatis tempor beatae unde cupidatat quis deserunt dolor ad excepteur ex. Veniam amet commodo nulla elit accusantium sit quia adipiscing consequat ratione. Ipsam odit veritatis magni est elit incididunt aliqua velit consequuntur lorem exercitation vitae fugit reprehenderit aperiam.",
  },
  {
    "pt-br": "– Ora, ora, ora, mas o que temos aqui...",
    en: "Magni quasi ut id esse excepteur commodo occaecat et excepteur est sint minim officia ex.",
  },
  {
    "pt-br": "– Blarinh, Senhor, um dos nossos...",
    en: "Vitae ipsum anim quia nostrud nesciunt amet ad dolorem nisi.",
  },
  {
    "pt-br": "– Não seja tolo, meu caro Rae, – Interrompeu o velho, – Se fosse um dos nossos, ele não estaria aqui, estaria? – Berdox o analisava cada vez mais de perto, farejando e analisando.",
    en: "Ab amet excepteur fugit magna eos deserunt incididunt occaecat. Illo do deserunt eu esse quisquam aliquip est. Illo pariatur aliqua cillum nisi odit elit quis quia. Accusantium aliqua officia enim duis sunt proident ea enim sit duis totam quia in cillum.",
  },
  {
    "pt-br": "Rae, um dos mascarados, não soube o que responder, nunca havia acontecido antes, então por prudência, permaneceu quieto.",
    en: "Consequat laborum ut velit mollit est labore enim omnis elit. Doloremque est dolorem irure et commodo consequuntur exercitation pariatur qui consequat.",
  },
  {
    "pt-br": "Berdox se abaixou um pouco e agarrou o prisioneiro pelo pescoço, o fazendo sufocar, em seguida, o encarou bem dentro de seus olhos tão profundamente que parecia estar lendo sua própria alma. – Você não está a sós aí dentro, está, Blarinh?",
    en: "Ex incididunt occaecat in sunt ad elit dolorem voluptas in aliqua. Officia neque unde eu omnis magna officia lorem. Irure quis pariatur qui consectetur proident laboris aute totam quis magna quia quis iste dolores aliquip. Exercitation eaque eiusmod dolorem tempor ipsa aspernatur perspiciatis magni aute.",
  },
  {
    "pt-br": "– Como... como pode saber? – Pensava o intruso, apavorado ao ser exposto daquela forma... ninguém nunca o havia percebido antes... Gargalhando alegremente, Berdox continuou, – Me lembro de você, criança... Blarinh... sim, me lembro bem de você... sempre contribuiu conosco, e então isso... não se preocupe, pequeno, logo estará de volta e tudo vai acabar bem...",
    en: "Ullamco magna quae beatae ipsam illo neque nostrud rem voluptate. Ipsum sed explicabo aspernatur iste proident quia voluptas elit iste neque. Cillum irure quia inventore amet perspiciatis tempor ipsum proident magni est magna beatae. Ea quis laudantium dolorem pariatur amet ad nemo excepteur totam eaque sit. Nulla iste deserunt iste do et nulla quia. Porro dolorem amet esse eos quia sint totam consequuntur elit in.",
  },
  {
    "pt-br": "– Desgraçados, estão se aproximando cada vez mais... – O velho e obscuro Berdox o soltou e em seguida lhe deu as costas, se afastando então, ordenou duramente, – Rae!",
    en: "Aspernatur perspiciatis deserunt omnis sit natus nesciunt error magna. Ea tempor nisi ab quis minim ut voluptate. Doloremque porro sit dolor incididunt nemo odit nostrud consequat dolor quia eaque.",
  },
  {
    "pt-br": "– Senhor.",
    en: "Iste ex nemo officia ut fugiat incididunt quia veniam consectetur duis et anim perspiciatis rem.",
  },
  {
    "pt-br": "– Temos um grande problema aqui... ordene que tragam um exorcista! [...]",
    en: "Magni aute labore et et non magna voluptatem aperiam aliquip amet aliquip aliqua beatae totam anim.",
  },
];